backend:
  name: git-gateway
  branch: main
media_folder: "images"
collections:
  - name: "stories"
    label: "Stories"
    folder: "stories"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Text", name: "text", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image"}